// repositories
export const FETCH_REPOSITORIES_SUCCESS = 'FETCH_REPOSITORIES_SUCCESS';
export const FETCH_REPOSITORIES_FAILED = 'FETCH_REPOSITORIES_FAILED';
export const FETCH_REPOSITORIES_START = 'FETCH_REPOSITORIES_START';

// codes
export const FETCH_CODES_SUCCESS = 'FETCH_CODES_SUCCESS';
export const FETCH_CODES_FAILED = 'FETCH_CODES_FAILED';
export const FETCH_CODES_START = 'FETCH_CODES_START';

// commits
export const FETCH_COMMITS_SUCCESS = 'FETCH_COMMITS_SUCCESS';
export const FETCH_COMMITS_FAILED = 'FETCH_COMMITS_FAILED';
export const FETCH_COMMITS_START = 'FETCH_COMMITS_START';

// issues
export const FETCH_ISSUES_SUCCESS = 'FETCH_ISSUES_SUCCESS';
export const FETCH_ISSUES_FAILED = 'FETCH_ISSUES_FAILED';
export const FETCH_ISSUES_START = 'FETCH_ISSUES_START';

// topics
export const FETCH_TOPICS_SUCCESS = 'FETCH_TOPICS_SUCCESS';
export const FETCH_TOPICS_FAILED = 'FETCH_TOPICS_FAILED';
export const FETCH_TOPICS_START = 'FETCH_TOPICS_START';

// labels
export const FETCH_LABELS_SUCCESS = 'FETCH_LABELS_SUCCESS';
export const FETCH_LABELS_FAILED = 'FETCH_LABELS_FAILED';
export const FETCH_LABELS_START = 'FETCH_LABELS_START';

// users
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED';
export const FETCH_USERS_START = 'FETCH_USERS_START';
